name: Docker Image Build and Push

on:
  push:
    branches:
      - main #test
        
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/planner-back-end:hopefully-works .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/planner-back-end:hopefully-works

      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}